### ISSUE TITLE
Wonderful Survey! And about Related Work

### ISSUE THREAD

**Issue by sdc17** [lijiannuist/Efficient-Multimodal-LLMs-Survey#1]
Hi, thank you for sharing this wonderful survey! It is very detailed and enlightening. Do you have any plans about incorporating the following works:
1. [CrossGET: Cross-Guided Ensemble of Tokens for Accelerating Vision-Language Transformers](https://arxiv.org/abs/2305.17455). arXiv 2023. To be appeared in ICML 2024.
2. [UPop: Unified and Progressive Pruning for Compressing Vision-Language Transformers](https://arxiv.org/abs/2301.13741). ICML 2023.

, which are related to the topic of efficient VLMs.

**Comment by sdc17** [comment]
By the way, it seems the paper link in README is incorrect:

https://github.com/lijiannuist/Efficient-Multimodal-LLMs-Survey/blob/39a58098ddac53ecacc4fc53e8b549fc1a8ffa3b/README.md?plain=1#L3

, the arXiv url given here is incomplete.

**Comment by lijiannuist** [comment]
> Hi, thank you for sharing this wonderful survey! It is very detailed and enlightening. Do you have any plans about incorporating the following works:
> 
> 1. [CrossGET: Cross-Guided Ensemble of Tokens for Accelerating Vision-Language Transformers](https://arxiv.org/abs/2305.17455). arXiv 2023. To be appeared in ICML 2024.
> 2. [UPop: Unified and Progressive Pruning for Compressing Vision-Language Transformers](https://arxiv.org/abs/2301.13741). ICML 2023.
> 
> , which are related to the topic of efficient VLMs.

**Comment by swordlidev** [comment]
Great works, We will include these papers in next version.

**Comment by swordlidev** [comment]
> By the way, it seems the paper link in README is incorrect:
> 
> https://github.com/lijiannuist/Efficient-Multimodal-LLMs-Survey/blob/39a58098ddac53ecacc4fc53e8b549fc1a8ffa3b/README.md?plain=1#L3
> 
> , the arXiv url given here is incomplete.

Thank you for your reminder
