### ISSUE TITLE
Link correction

### ISSUE THREAD

**Issue by E-crls** [lijiannuist/Efficient-Multimodal-LLMs-Survey#2]
The link in the excerpt below leads to a paper called: "Hyper-algebraic invariants of p-adic algebraic numbers"
Moe-llava: Mixture of experts for large vision-language models. arXiv, 2024 [[Paper](https://arxiv.org/abs/2402.15947)]

The correct link is:
https://arxiv.org/abs/2401.15947

**Comment by jinyizhang184** [comment]
Thank you for reporting this issue! I have already fixed the error and submitted the corresponding changes.
