### ISSUE TITLE
Wonderful Survey! Add of a new work. 

### ISSUE THREAD

**Issue by gordonhu608** [lijiannuist/Efficient-Multimodal-LLMs-Survey#3]
Thanks for the wonderful survey. We would like to add a new work: Matryoshka Query Transformer for Large Vision-Language Models. Paper: https://arxiv.org/abs/2405.19315 code: https://github.com/gordonhu608/MQT-LLaVA. 
This model adds a new perspective in efficiently utilize visual tokens for Multimodal LLMs. Thank you so much ahead for considering our work.

**Comment by swordlidev** [comment]
Great work, We have added it to this repo and will include the paper in our next version.
