### ISSUE TITLE
Excellent  survey!  Adding a new work.

### ISSUE THREAD

**Issue by LiWentomng** [lijiannuist/Efficient-Multimodal-LLMs-Survey#4]
Thanks for the excellent survey!

Would you like include a new work: TokenPacker: Efficient Visual Projector for Multimodal LLM.

Paper: https://arxiv.org/abs/2407.02392
Code: https://github.com/CircleRadon/TokenPacker

This work provides a new VL projector to reduce the visual tokens for effeicient Multimodal LLMs.
 
Thank you in advance for considering our work.

**Comment by swordlidev** [comment]
Great work, We have added it to this repo and will include the paper in our next version.

**Comment by LiWentomng** [comment]
@SwordliCoder  Thanks!  We will cite your survey  work in our final version.
